/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "乘以三的尝试",
  "description": "菜鸟的尝试",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": null,
        "heroText": null
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7c812c3c",
      "path": "/",
      "lastUpdated": "3 天前",
      "lastUpdatedTimestamp": 1681713405000
    },
    {
      "frontmatter": {},
      "regularPath": "/blogs/2.html",
      "relativePath": "blogs/2.md",
      "key": "v-700367d2",
      "path": "/blogs/2.html",
      "headers": [
        {
          "level": 2,
          "title": "publish: false",
          "slug": "publish-false"
        }
      ],
      "lastUpdated": "3 天前",
      "lastUpdatedTimestamp": 1681713405000
    },
    {
      "title": "demo演示",
      "frontmatter": {
        "title": "demo演示",
        "date": "2023-4-12",
        "sticky": 1,
        "publish": false
      },
      "regularPath": "/blogs/1.html",
      "relativePath": "blogs/1.md",
      "key": "v-1da4b132",
      "path": "/blogs/1.html",
      "lastUpdated": "6 天前",
      "lastUpdatedTimestamp": 1681452904000
    },
    {
      "title": "hello css",
      "frontmatter": {},
      "regularPath": "/blogs/css/1.html",
      "relativePath": "blogs/css/1.md",
      "key": "v-33645025",
      "path": "/blogs/css/1.html",
      "headers": [
        {
          "level": 2,
          "title": "demo",
          "slug": "demo"
        },
        {
          "level": 2,
          "title": "demo2",
          "slug": "demo2"
        }
      ],
      "lastUpdated": "7 天前",
      "lastUpdatedTimestamp": 1681374264000
    },
    {
      "title": "hello js",
      "frontmatter": {},
      "regularPath": "/blogs/js/1.html",
      "relativePath": "blogs/js/1.md",
      "key": "v-674fd5ce",
      "path": "/blogs/js/1.html",
      "headers": [
        {
          "level": 2,
          "title": "新的标题",
          "slug": "新的标题"
        }
      ],
      "lastUpdated": "7 天前",
      "lastUpdatedTimestamp": 1681376777000
    },
    {
      "title": "介绍",
      "frontmatter": {
        "title": "介绍",
        "date": "2023-4-14",
        "publish": false
      },
      "regularPath": "/blogs/",
      "relativePath": "blogs/README.md",
      "key": "v-7a7380e5",
      "path": "/blogs/",
      "lastUpdated": "3 天前",
      "lastUpdatedTimestamp": 1681713405000
    },
    {
      "title": "重头开始搭建",
      "frontmatter": {
        "title": "重头开始搭建",
        "date": "2023-4-18"
      },
      "regularPath": "/start/",
      "relativePath": "start/README.md",
      "key": "v-48d84efa",
      "path": "/start/",
      "headers": [
        {
          "level": 2,
          "title": "本地搭建",
          "slug": "本地搭建"
        },
        {
          "level": 2,
          "title": "基础配置",
          "slug": "基础配置"
        },
        {
          "level": 3,
          "title": "添加标题和描述，方便之后SEO",
          "slug": "添加标题和描述-方便之后seo"
        }
      ],
      "excerpt": "<h1 id=\"前言\"><a class=\"header-anchor\" href=\"#前言\">#</a> 前言</h1>\n<div class=\"custom-block tip\"><p class=\"title\"></p><p>某日网上冲浪心血来潮想搭建一个博客，最初只是想记录面试过程中遇到的问题和理解，以及平时学习过程中的笔记。\n在网上参照<a href=\"https://github.com/mqyqingfeng/Blog\" target=\"_blank\" rel=\"noopener noreferrer\">冴羽github<OutboundLink/></a>/<a href=\"https://zhuanlan.zhihu.com/p/489776067\" target=\"_blank\" rel=\"noopener noreferrer\">冴羽知乎<OutboundLink/></a>的教程，\n搭建了该平台，在此感谢大佬的指点。</p>\n</div><p>记录下搭建的过程和在过程中遇到的问题及找到的解答。</p>\n"
    },
    {
      "title": "hello",
      "frontmatter": {},
      "regularPath": "/blogs/vue/1.html",
      "relativePath": "blogs/vue/1.md",
      "key": "v-f01adaf6",
      "path": "/blogs/vue/1.html",
      "lastUpdated": "6 天前",
      "lastUpdatedTimestamp": 1681452904000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "author": "chengyisan",
    "logo": "/logo.png",
    "type": "BlogHome",
    "lastUpdated": "上次更新",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "搭建",
        "link": "/start/"
      },
      {
        "text": "文档",
        "link": "/blogs/"
      },
      {
        "text": "关于我",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/1121946905352599",
            "icon": "reco-juejin"
          },
          {
            "text": "Github",
            "link": "https://github.com/Pine-Nuts",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "subSidebar": "auto",
    "sidebar": {
      "/blogs/": [
        {
          "title": "基础",
          "collapsable": false,
          "children": [
            {
              "title": "介绍",
              "path": "/blogs/"
            },
            {
              "title": "CSS",
              "path": "/blogs/css/1"
            },
            {
              "title": "JavaScript",
              "path": "/blogs/js/1"
            },
            {
              "title": "Vue",
              "path": "/blogs/vue/1"
            }
          ]
        }
      ]
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}