/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "乘以三的博客",
  "description": "菜鸟的尝试",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "第一遍",
      "frontmatter": {
        "title": "第一遍",
        "date": "2023-4-12"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7c812c3c",
      "path": "/"
    },
    {
      "title": "demo演示",
      "frontmatter": {
        "title": "demo演示",
        "date": "2023-4-12",
        "categories": [
          "随笔"
        ],
        "tags": [
          "demo"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/1.html",
      "relativePath": "blogs/1.md",
      "key": "v-1da4b132",
      "path": "/blogs/1.html"
    },
    {
      "title": "hello js",
      "frontmatter": {},
      "regularPath": "/blogs/js/1.html",
      "relativePath": "blogs/js/1.md",
      "key": "v-674fd5ce",
      "path": "/blogs/js/1.html"
    },
    {
      "title": "hello css",
      "frontmatter": {},
      "regularPath": "/blogs/css/1.html",
      "relativePath": "blogs/css/1.md",
      "key": "v-33645025",
      "path": "/blogs/css/1.html",
      "headers": [
        {
          "level": 2,
          "title": "demo",
          "slug": "demo"
        },
        {
          "level": 2,
          "title": "demo2",
          "slug": "demo2"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blogs/2.html",
      "relativePath": "blogs/2.md",
      "key": "v-700367d2",
      "path": "/blogs/2.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "demo Tags"
      },
      "regularPath": "/tag/demo/",
      "key": "v-1528037c",
      "path": "/tag/demo/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "随笔 Categories"
      },
      "regularPath": "/categories/%E9%9A%8F%E7%AC%94/",
      "key": "v-2bf76980",
      "path": "/categories/随笔/"
    }
  ],
  "themeConfig": {
    "author": "chengyisan",
    "logo": "/logo.png",
    "type": "blog",
    "lastUpdated": "上次更新",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "关于我",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/1121946905352599"
          },
          {
            "text": "Github",
            "link": "https://github.com/Pine-Nuts"
          }
        ]
      }
    ],
    "subSidebar": "auto",
    "sidebar": [
      {
        "title": "欢迎学习",
        "path": "/",
        "collapsable": false,
        "children": [
          {
            "title": "博客简介",
            "path": "/"
          }
        ]
      },
      {
        "title": "基础篇",
        "collapsable": true,
        "children": [
          {
            "title": "CSS",
            "path": "/blogs/css/1"
          },
          {
            "title": "JS",
            "path": "/blogs/js/1"
          }
        ]
      }
    ],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "博客"
      },
      "tag": {
        "location": 4,
        "text": "标签"
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}