/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "乘以三的博客",
  "description": "菜鸟的尝试",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": null,
        "heroText": null
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7c812c3c",
      "path": "/",
      "lastUpdated": "3 天前",
      "lastUpdatedTimestamp": 1681452904000
    },
    {
      "title": "demo演示",
      "frontmatter": {
        "title": "demo演示",
        "date": "2023-4-12",
        "categories": [
          "随笔"
        ],
        "tags": [
          "demo"
        ],
        "sticky": 1,
        "publish": false
      },
      "regularPath": "/blogs/1.html",
      "relativePath": "blogs/1.md",
      "key": "v-1da4b132",
      "path": "/blogs/1.html",
      "lastUpdated": "3 天前",
      "lastUpdatedTimestamp": 1681452904000
    },
    {
      "title": "hello css",
      "frontmatter": {},
      "regularPath": "/blogs/css/1.html",
      "relativePath": "blogs/css/1.md",
      "key": "v-33645025",
      "path": "/blogs/css/1.html",
      "headers": [
        {
          "level": 2,
          "title": "demo",
          "slug": "demo"
        },
        {
          "level": 2,
          "title": "demo2",
          "slug": "demo2"
        }
      ],
      "lastUpdated": "4 天前",
      "lastUpdatedTimestamp": 1681374264000
    },
    {
      "title": "介绍",
      "frontmatter": {
        "title": "介绍",
        "date": "2023-4-14",
        "publish": false
      },
      "regularPath": "/blogs/",
      "relativePath": "blogs/README.md",
      "key": "v-7a7380e5",
      "path": "/blogs/",
      "lastUpdated": "3 天前",
      "lastUpdatedTimestamp": 1681453245000
    },
    {
      "title": "hello",
      "frontmatter": {},
      "regularPath": "/blogs/vue/1.html",
      "relativePath": "blogs/vue/1.md",
      "key": "v-f01adaf6",
      "path": "/blogs/vue/1.html",
      "lastUpdated": "3 天前",
      "lastUpdatedTimestamp": 1681452904000
    },
    {
      "title": "hello js",
      "frontmatter": {},
      "regularPath": "/blogs/js/1.html",
      "relativePath": "blogs/js/1.md",
      "key": "v-674fd5ce",
      "path": "/blogs/js/1.html",
      "headers": [
        {
          "level": 2,
          "title": "新的标题",
          "slug": "新的标题"
        }
      ],
      "lastUpdated": "4 天前",
      "lastUpdatedTimestamp": 1681376777000
    },
    {
      "frontmatter": {},
      "regularPath": "/blogs/2.html",
      "relativePath": "blogs/2.md",
      "key": "v-700367d2",
      "path": "/blogs/2.html",
      "lastUpdated": "3 天前",
      "lastUpdatedTimestamp": 1681452904000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "demo Tags"
      },
      "regularPath": "/tag/demo/",
      "key": "v-1528037c",
      "path": "/tag/demo/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "随笔 Categories"
      },
      "regularPath": "/categories/%E9%9A%8F%E7%AC%94/",
      "key": "v-2bf76980",
      "path": "/categories/随笔/"
    }
  ],
  "themeConfig": {
    "author": "chengyisan",
    "logo": "/logo.png",
    "authorAvatar": "/avatar.png",
    "type": "BlogHome",
    "lastUpdated": "上次更新",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "文档",
        "link": "/blogs/"
      },
      {
        "text": "关于我",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/1121946905352599",
            "icon": "reco-juejin"
          },
          {
            "text": "Github",
            "link": "https://github.com/Pine-Nuts",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "subSidebar": "auto",
    "sidebar": {
      "/blogs/": [
        {
          "title": "基础",
          "collapsable": false,
          "children": [
            {
              "title": "介绍",
              "path": "/blogs/"
            },
            {
              "title": "CSS",
              "path": "/blogs/css/1"
            },
            {
              "title": "JavaScript",
              "path": "/blogs/js/1"
            },
            {
              "title": "Vue",
              "path": "/blogs/vue/1"
            }
          ]
        }
      ]
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}