/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "demo": {
      "key": "demo",
      "scope": "tags",
      "path": "/tag/demo/",
      "pageKeys": [
        "v-1da4b132"
      ]
    }
  },
  "categories": {
    "随笔": {
      "key": "随笔",
      "scope": "categories",
      "path": "/categories/随笔/",
      "pageKeys": [
        "v-1da4b132"
      ]
    }
  },
  "timeline": {}
}